import type { ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { Vault } from "lucide-react";
import { Navbar } from "./navbar";

export function SiteLayout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navbar />
      <main className="pt-24 flex-1">{children}</main>
      <SiteFooter />
    </div>
  );
}

export function SiteFooter() {
  return (
    <footer className="border-t border-border mt-16">
      <div className="mx-auto max-w-6xl px-6 py-10 grid gap-6 md:grid-cols-[1fr_auto] items-start">
        <div>
          <Link to="/" className="inline-flex items-center gap-2">
            <span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-cyan glow-cyan">
              <Vault className="h-4 w-4 text-primary-foreground" />
            </span>
            <span className="text-lg font-bold tracking-tight">
              <span className="text-foreground">Vault</span><span className="text-gradient-cyan">IQ</span>
            </span>
          </Link>
          <p className="mt-2 text-sm text-muted-foreground">Your financial future, unlocked.</p>
          <p className="mt-4 max-w-xl text-xs text-muted-foreground">
            VaultIQ is an educational AI tool. All predictions are generated by rule-based algorithms
            and do not constitute official financial or banking advice.
          </p>
        </div>
        <nav className="flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground md:justify-end">
          <Link to="/" className="hover:text-foreground">Home</Link>
          <Link to="/" hash="apply" className="hover:text-foreground">Apply</Link>
          <Link to="/emi" className="hover:text-foreground">EMI</Link>
          <Link to="/compare" className="hover:text-foreground">Compare</Link>
          <Link to="/dashboard" className="hover:text-foreground">Dashboard</Link>
          <Link to="/history" className="hover:text-foreground">History</Link>
        </nav>
      </div>
      <div className="border-t border-border py-4 text-center text-xs text-muted-foreground">
        © 2024 VaultIQ. All rights reserved.
      </div>
    </footer>
  );
}
